Repository wecode-bootcamp-korea/24-1st-RS-frontend, pull requests merged in 2021-09, with the labels that each got.

#2 [김동희] FIX : 코드 리팩토링
  public/images/Signup/signup-idcard.png
  src/pages/Signin/Signin.scss
  src/pages/Signup/Signup.js
  src/pages/Signup/Signup.scss
Labels: Status: 리뷰 요청

#3 [김동희] FIX : 코드 리팩토링
  src/pages/Signin/GoogleButton.js
  src/pages/Signin/KakaoButton.js
  src/pages/Signin/NaverButton.js
  src/pages/Signin/Signin.js
  src/pages/Signin/Signin.scss
Labels: Status: 리뷰 요청, Status: 추가 기능 구현중

#7 [김동희] ADD : 공통 스타일링 요소 추가
  src/pages/Category/Category.scss
  src/pages/Signup/Signup.js
  src/pages/Signup/Signup.scss
  src/styles/common.scss
Labels: Status: 리뷰 요청

#8 [김동희] Refactor : 로그인 성공/실패 alert 구현 로직 변경 및 API변수화
  src/config.js
  src/pages/Signin/Signin.js
  src/pages/Signin/Signin.scss
Labels: Status: 리뷰 요청

#6 [김동희] FIX : 불필요해진 코드 및 console 정리
  src/config.js
  src/pages/Signup/Signup.js
  src/pages/Signup/Signup.scss
Labels: Status: 리뷰 요청

#11 [지의선] ADD: base관련 이미지 및 alt 컴포넌트화 완료
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
  src/components/Footer/FooterComp.js
Labels: Status: Accepted

#9 [김동희] ADD/Refactor : product hover일 때 새로운 요소 나타내기 추가, 코드 리팩토링
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
  src/config.js
  src/pages/Category/Category.js
  src/pages/Category/Category.scss
  src/pages/Category/Filter.js
  src/pages/Category/FilterBtn.js
  src/pages/Category/Mainimage.js
  src/pages/Category/Maintext.js
  src/pages/Category/Product.js
  src/pages/Category/Productlist.js
  src/pages/Category/Reviewstar.js
  src/pages/Category/filterBtnData.js
  src/pages/Category/takju.png
  src/pages/Signin/Signin.js
  src/pages/Signup/Signup.js
Labels: Status: 리뷰 요청

#5 [강연옥] [merge 요청]ADD: Detail페이지 필수구현기능 완료
  src/Routes.js
  src/config.js
  src/pages/Cart/Cart.js
  src/pages/Cart/Modal.js
  src/pages/Category/Category.js
  src/pages/Details/AddToCart.js
  src/pages/Details/Details.js
  src/pages/Details/Details.scss
  src/pages/Details/Features.js
  src/pages/Details/ProductDetails.js
  src/pages/Details/ProductInfo.js
  src/pages/Details/Shipping.js
  src/pages/Details/SideDishes.js
  src/pages/Details/Tasting.js
  src/pages/Main/Main.js
  src/pages/Signin/Signin.js
  src/pages/Signup/Signup.js
  src/styles/common.scss
Labels: Status: 리뷰 요청

#14 [김동희] ADD : 동적 라우팅 연결, 안주로 상품 검색 기능 추가
  src/Routes.js
  src/pages/Category/Category.js
  src/pages/Category/Category.scss
  src/pages/Category/Filter.js
  src/pages/Category/Product.js
  src/pages/Category/Productlist.js
  src/pages/Signin/Signin.js
  src/pages/Signup/Signup.js
  src/pages/Signup/Signup.scss
Labels: Status: 리뷰 요청

#13 [지의선]Refactor : 동적라우팅 연결을 위한 코드 정리 및 상세페이지 내 디자인 요소 추가
  src/Routes.js
  src/components/Nav/Nav.js
  src/pages/Category/Category.scss
  src/pages/Category/Product.js
  src/pages/Details/Details.js
  src/pages/Details/Details.scss
  src/pages/Details/Features.js
  src/pages/Details/SideDishes.js
  src/pages/Details/Tasting.js
  src/pages/Main/Banner.js
  src/pages/Main/BannerSliderData.js
  src/pages/Main/BestItem.scss
  src/pages/Main/BestItemComp.js
  src/pages/Main/BestItemCompDetail.js
  src/pages/Main/FirstItemComp.js
  src/pages/Main/Holiday.js
  src/pages/Main/MENU_DATA.js
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
  src/pages/Main/Menu.js
  src/pages/Main/MenuDetail.js
  src/pages/Main/NewItemComp.js
  src/pages/Main/NewItemCompDetail.js
  src/pages/Main/ProductsCard.js
  src/pages/Main/Recommendation.js
  src/pages/Main/Recommendations.scss
  src/pages/Main/Time.js
Labels: Status: 리뷰 요청

#16 [지의선] ADD: 사진 랜덤으로 받아오기 (조건부 렌더링 사용)
  src/pages/Main/CountDown.js
  src/pages/Main/Main.js
  src/pages/Main/Recommendation.js
  src/pages/Main/Recommendations.scss
  src/pages/Main/Time.js
Labels: Status: Accepted

#17 [김동희] ADD : input 값 입력시 색상 변화
  src/pages/Signin/Signin.js
  src/pages/Signin/Signin.scss
Labels: Status: 리뷰 요청

#18 ADD : 기능 구현 에러 수정 완료
  src/config.js
  src/pages/Cart/Modal.js
  src/pages/Details/SideDishes.js
  src/pages/Details/Tasting.js
Labels: Status: 리뷰 요청
